from __future__ import annotations

from sqlalchemy import Column, Date, Integer, Numeric, String, TIMESTAMP

from db.base import Base


class Item(Base):
    __tablename__ = "item"

    li_item_id = Column(String(100), primary_key=True)
    schedule_code = Column(String(20))
    drug_name = Column(String(500))
    li_drug_name = Column(String(500))
    li_form = Column(String(500))
    schedule_form = Column(String(500))
    brand_name = Column(String(500))
    program_code = Column(String(10))
    pbs_code = Column(String(20))
    benefit_type_code = Column(String(1))
    caution_indicator = Column(String(1))
    note_indicator = Column(String(1))
    manner_of_administration = Column(String(100))
    moa_preferred_term = Column(String(100))
    maximum_prescribable_pack = Column(Integer)
    maximum_quantity_units = Column(String(50))
    number_of_repeats = Column(Integer)
    organisation_id = Column(Integer)
    manufacturer_code = Column(String(20))
    pack_size = Column(Integer)
    pricing_quantity = Column(Integer)
    pack_not_to_be_broken_ind = Column(String(1))
    claimed_price = Column(Numeric(10, 2))
    determined_price = Column(Numeric(10, 2))
    determined_qty = Column(String(1))
    safety_net_resupply_rule_days = Column(Integer)
    safety_net_resup_rule_cnt_ind = Column(String(1))
    extemporaneous_indicator = Column(String(1))
    extemporaneous_standard = Column(String(100))
    doctors_bag_group_id = Column(String(50))
    section100_only_indicator = Column(String(1))
    doctors_bag_only_indicator = Column(String(1))
    brand_substitution_group_id = Column(String(50))
    brand_substitution_group_code = Column(String(10))
    continued_dispensing_emergency = Column(String(1))
    continued_dispensing_flag = Column(String(1))
    supply_only_indicator = Column(String(1))
    supply_only_date = Column(Date)
    non_effective_date = Column(Date)
    originator_brand_indicator = Column(String(1))
    paper_med_chart_eligible_ind = Column(String(1))
    elect_med_chart_eligible_ind = Column(String(1))
    hsptl_med_chart_eligible_ind = Column(String(1))
    paper_med_chart_duration = Column(Integer)
    elect_med_chart_duration = Column(Integer)
    hsptl_chart_acute_duration = Column(Integer)
    hsptl_chart_sub_acute_duration = Column(Integer)
    hsptl_chart_chronic_duration = Column(Integer)
    pack_content = Column(Integer)
    vial_content = Column(String(50))
    infusible_indicator = Column(String(1))
    unit_of_measure = Column(String(50))
    maximum_amount = Column(String(50))
    formulary = Column(String(10))
    water_added_ind = Column(String(1))
    section_19a_expiry_date = Column(Date)
    container_fee_type = Column(String(50))
    policy_applied_bio_sim_up_flag = Column(String(1))
    policy_applied_imdq60_flag = Column(String(1))
    policy_applied_imdq60_base_flag = Column(String(1))
    policy_applied_indig_phar_flag = Column(String(1))
    therapeutic_exemption_indicator = Column(String(1))
    premium_exemption_group_id = Column(String(50))
    doctors_bag_group_title = Column(String(200))
    therapeutic_group_id = Column(String(50))
    therapeutic_group_title = Column(String(200))
    advanced_notice_date = Column(Date)
    supply_only_end_date = Column(Date)
    first_listed_date = Column(Date)
    legal_unar_ind = Column(String(1))
    legal_car_ind = Column(String(1))
    proportional_price = Column(Numeric(10, 2))
    li_substitution_group_id = Column(String(50))
    innovator_indicator = Column(String(1))
    created_at = Column(TIMESTAMP)
    updated_at = Column(TIMESTAMP)
