from __future__ import annotations

from db.models import (
    ATCCode,
    AMTItem,
    BaseReference,
    Container,
    ContainerOrganisationRelationship,
    Copayment,
    Criterion,
    CriteriaParameterRelationship,
    DispensingRule,
    ExtemporaneousIngredient,
    ExtemporaneousPreparation,
    ExtemporaneousTariff,
    ExtPrepSfpRelationship,
    Fee,
    Indication,
    Item,
    ItemDispensingRuleRelationship,
    ItemAtcRelationship,
    ItemOrganisationRelationship,
    ItemPrescribingTextRelationship,
    ItemPricingEvent,
    ItemRestrictionRelationship,
    MarkupBand,
    Organisation,
    Parameter,
    Prescriber,
    PrescribingText,
    Program,
    ProgramDispensingRule,
    Restriction,
    RestrictionPrescribingTextRelationship,
    Schedule,
    StandardFormulaPreparation,
    SummaryOfChange,
)

STATIC_ENDPOINTS = {
    "atc-codes",
    "organisations",
    "containers",
    "programs",
    "schedules",
    "prescribing-texts",
}

SYNC_PLAN = {
    "schedules": {"model": Schedule, "key_fields": ["schedule_code"], "is_static": True},
    "summary-of-changes": {"model": SummaryOfChange, "key_fields": ["schedule_code", "source_schedule_code", "changed_table", "table_keys"]},
    "programs": {"model": Program, "key_fields": ["program_code", "schedule_code"], "is_static": True},
    "organisations": {"model": Organisation, "key_fields": ["organisation_id", "schedule_code"], "is_static": True},
    "containers": {"model": Container, "key_fields": ["container_code", "schedule_code"], "is_static": True},
    "atc-codes": {"model": ATCCode, "key_fields": ["atc_code", "schedule_code"], "is_static": True},
    "dispensing-rules": {"model": DispensingRule, "key_fields": ["dispensing_rule_reference", "schedule_code"]},
    "criteria": {"model": Criterion, "key_fields": ["criteria_prescribing_txt_id", "schedule_code"]},
    "parameters": {"model": Parameter, "key_fields": ["parameter_prescribing_txt_id", "schedule_code"]},
    "prescribing-texts": {"model": PrescribingText, "key_fields": ["prescribing_txt_id", "schedule_code"], "is_static": True},
    "indications": {"model": Indication, "key_fields": ["indication_prescribing_txt_id", "schedule_code"]},
    "copayments": {"model": Copayment, "key_fields": ["id", "schedule_code"]},
    "fees": {"model": Fee, "key_fields": ["id", "schedule_code", "program_code"]},
    "restrictions": {"model": Restriction, "key_fields": ["res_code", "schedule_code"]},
    "items": {"model": Item, "key_fields": ["li_item_id", "schedule_code"]},
    "prescribers": {"model": Prescriber, "key_fields": ["pbs_code", "prescriber_code", "schedule_code"]},
    "markup-bands": {"model": MarkupBand, "key_fields": ["program_code", "dispensing_rule_mnem", "markup_band_code", "schedule_code", "limit"]},
    "extemporaneous-tariffs": {"model": ExtemporaneousTariff, "key_fields": ["pbs_code", "schedule_code"]},
    "extemporaneous-ingredients": {"model": ExtemporaneousIngredient, "key_fields": ["pbs_code", "schedule_code"]},
    "extemporaneous-preparations": {"model": ExtemporaneousPreparation, "key_fields": ["schedule_code", "preparation"]},
    "standard-formula-preparations": {"model": StandardFormulaPreparation, "key_fields": ["pbs_code", "schedule_code"]},
    "item-pricing-events": {"model": ItemPricingEvent, "key_fields": ["li_item_id", "schedule_code", "event_type_code"]},
    "amt-items": {"model": AMTItem, "key_fields": ["pbs_concept_id", "schedule_code", "li_item_id"]},
    "item-atc-relationships": {"model": ItemAtcRelationship, "key_fields": ["atc_code", "pbs_code", "schedule_code"]},
    "item-organisation-relationships": {"model": ItemOrganisationRelationship, "key_fields": ["pbs_code", "organisation_id", "schedule_code"]},
    "item-restriction-relationships": {"model": ItemRestrictionRelationship, "key_fields": ["pbs_code", "res_code", "schedule_code"]},
    "item-dispensing-rule-relationships": {"model": ItemDispensingRuleRelationship, "key_fields": ["li_item_id", "dispensing_rule_reference", "schedule_code"]},
    "item-prescribing-text-relationships": {"model": ItemPrescribingTextRelationship, "key_fields": ["pbs_code", "prescribing_txt_id", "schedule_code"]},
    "restriction-prescribing-text-relationships": {"model": RestrictionPrescribingTextRelationship, "key_fields": ["res_code", "prescribing_text_id", "schedule_code"]},
    "criteria-parameter-relationships": {"model": CriteriaParameterRelationship, "key_fields": ["criteria_prescribing_txt_id", "parameter_prescribing_txt_id", "schedule_code"]},
    "container-organisation-relationships": {"model": ContainerOrganisationRelationship, "key_fields": ["container_code", "organisation_id", "schedule_code"]},
    "extemporaneous-prep-sfp-relationships": {"model": ExtPrepSfpRelationship, "key_fields": ["sfp_pbs_code", "ex_prep_pbs_code", "schedule_code"]},
    "program-dispensing-rules": {"model": ProgramDispensingRule, "key_fields": ["program_code", "dispensing_rule_mnem", "schedule_code"]},
}
