"""add_dedicated_models

Revision ID: ae2351fa6f28
Revises: bfb9b4e35082
Create Date: 2026-01-26 01:40:01.148898
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae2351fa6f28"
down_revision = 'bfb9b4e35082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amt_item',
    sa.Column('pbs_concept_id', sa.String(length=50), nullable=False),
    sa.Column('concept_type_code', sa.String(length=20), nullable=True),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('amt_code', sa.String(length=50), nullable=True),
    sa.Column('li_item_id', sa.String(length=100), nullable=True),
    sa.Column('preferred_term', sa.String(length=500), nullable=True),
    sa.Column('exempt_ind', sa.String(length=1), nullable=True),
    sa.Column('non_amt_code', sa.String(length=50), nullable=True),
    sa.Column('pbs_preferred_term', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_concept_id', 'schedule_code')
    )
    op.create_table('container',
    sa.Column('container_code', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('container_name', sa.String(length=500), nullable=True),
    sa.Column('mark_up', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('agreed_purchasing_unit', sa.String(length=50), nullable=True),
    sa.Column('average_exact_unit_price', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('average_rounded_unit_price', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('container_type', sa.String(length=100), nullable=True),
    sa.Column('container_quantity', sa.String(length=50), nullable=True),
    sa.Column('container_unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('container_code', 'schedule_code')
    )
    op.create_table('container_organisation_relationships',
    sa.Column('container_code', sa.String(length=20), nullable=False),
    sa.Column('organisation_id', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('container_code', 'organisation_id', 'schedule_code')
    )
    op.create_table('criteria_parameter_relationships',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('criteria_prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('parameter_prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('pt_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('criteria_prescribing_txt_id', 'parameter_prescribing_txt_id', 'schedule_code')
    )
    op.create_table('criterion',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('criteria_prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('criteria_type', sa.String(length=100), nullable=True),
    sa.Column('parameter_relationship', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'criteria_prescribing_txt_id')
    )
    op.create_table('dispensing_rule',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('dispensing_rule_mnem', sa.String(length=100), nullable=False),
    sa.Column('dispensing_rule_reference', sa.String(length=100), nullable=False),
    sa.Column('dispensing_rule_title', sa.String(length=200), nullable=True),
    sa.Column('community_pharmacy_indicator', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'dispensing_rule_mnem', 'dispensing_rule_reference')
    )
    op.create_table('extemporaneous_ingredient',
    sa.Column('pbs_code', sa.String(length=50), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('agreed_purchasing_unit', sa.String(length=50), nullable=True),
    sa.Column('exact_tenth_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_one_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_ten_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_hundred_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_tenth_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_one_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_ten_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_hundred_gram_per_ml_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'schedule_code')
    )
    op.create_table('extemporaneous_prep_sfp_relationships',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('sfp_pbs_code', sa.String(length=50), nullable=False),
    sa.Column('ex_prep_pbs_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sfp_pbs_code', 'ex_prep_pbs_code', 'schedule_code')
    )
    op.create_table('extemporaneous_preparation',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('preparation', sa.String(length=500), nullable=False),
    sa.Column('pbs_code', sa.String(length=50), nullable=False),
    sa.Column('maximum_quantity', sa.String(length=50), nullable=True),
    sa.Column('maximum_quantity_unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'preparation', 'pbs_code')
    )
    op.create_table('extemporaneous_tariff',
    sa.Column('pbs_code', sa.String(length=50), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('drug_name', sa.String(length=500), nullable=True),
    sa.Column('agreed_purchasing_unit', sa.String(length=50), nullable=True),
    sa.Column('markup', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rounded_rec_one_tenth_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_rec_one_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_rec_ten_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rounded_rec_hundred_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_rec_one_tenth_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_rec_one_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_rec_ten_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exact_rec_hundred_gram', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'schedule_code')
    )
    op.create_table('item_atc_relationships',
    sa.Column('atc_code', sa.String(length=20), nullable=False),
    sa.Column('pbs_code', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('atc_priority_pct', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('atc_code', 'pbs_code', 'schedule_code')
    )
    op.create_table('item_dispensing_rule_relationships',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('dispensing_rule_mnem', sa.String(length=100), nullable=True),
    sa.Column('dispensing_rule_reference', sa.String(length=100), nullable=False),
    sa.Column('brand_premium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispense_fee_type_code', sa.String(length=10), nullable=True),
    sa.Column('dangerous_drug_fee_code', sa.String(length=10), nullable=True),
    sa.Column('therapeutic_group_premium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cmnwlth_price_to_pharmacist', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('man_price_to_pharmacist', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('man_dispnsd_price_max_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_record_val_for_safety_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cmnwlth_dsp_price_max_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tgm_price_phrmcst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tgm_disp_price_max_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('special_patient_contribution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_dispensing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_dispensing_ex', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_dispensing_dd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_water', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_container_injectable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_container_other', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_safety_net_recording', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_safety_net_recording_ex', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_chemo_flat_wholesale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_chemo_prep', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_diluent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('submitted_pharmacists_pack_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_general_patient_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mn_price_dispenser', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mn_price_wholesale_markup_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mn_price_wholesale_markup_code', sa.String(length=10), nullable=True),
    sa.Column('mn_price_wholesale_markup', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mn_pharmacy_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mn_pharmacy_markup_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mn_pharmacy_markup_code', sa.String(length=10), nullable=True),
    sa.Column('mn_pharmacy_markup', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('li_item_id', 'dispensing_rule_reference', 'schedule_code')
    )
    op.create_table('item_organisation_relationships',
    sa.Column('pbs_code', sa.String(length=20), nullable=False),
    sa.Column('organisation_id', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('pbs_code', 'organisation_id', 'schedule_code')
    )
    op.create_table('item_prescribing_text_relationships',
    sa.Column('pbs_code', sa.String(length=20), nullable=False),
    sa.Column('prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('pt_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'prescribing_txt_id', 'schedule_code')
    )
    op.create_table('item_pricing_event',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('percentage_applied', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('event_type_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'li_item_id')
    )
    op.create_table('item_restriction_relationships',
    sa.Column('res_code', sa.String(length=100), nullable=False),
    sa.Column('pbs_code', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('benefit_type_code', sa.String(length=1), nullable=True),
    sa.Column('restriction_indicator', sa.String(length=1), nullable=True),
    sa.Column('res_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('res_code', 'pbs_code', 'schedule_code')
    )
    op.create_table('markup_band',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('program_code', sa.String(length=10), nullable=False),
    sa.Column('dispensing_rule_mnem', sa.String(length=100), nullable=False),
    sa.Column('markup_band_code', sa.String(length=50), nullable=False),
    sa.Column('limit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('variable', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('offset', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fixed', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'program_code', 'dispensing_rule_mnem', 'markup_band_code')
    )
    op.create_table('parameter',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('parameter_prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=True),
    sa.Column('parameter_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'parameter_prescribing_txt_id')
    )
    op.create_table('prescriber',
    sa.Column('pbs_code', sa.String(length=50), nullable=False),
    sa.Column('prescriber_code', sa.String(length=10), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('prescriber_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'prescriber_code', 'schedule_code')
    )
    op.create_table('program',
    sa.Column('program_code', sa.String(length=10), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('program_title', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('program_code', 'schedule_code')
    )
    op.create_table('program_dispensing_rules',
    sa.Column('program_code', sa.String(length=10), nullable=False),
    sa.Column('dispensing_rule_mnem', sa.String(length=100), nullable=False),
    sa.Column('default_indicator', sa.String(length=1), nullable=True),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('program_code', 'dispensing_rule_mnem', 'schedule_code')
    )
    op.create_table('restriction_prescribing_text_relationships',
    sa.Column('res_code', sa.String(length=100), nullable=False),
    sa.Column('prescribing_txt_id', sa.String(length=50), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('pt_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('res_code', 'prescribing_txt_id', 'schedule_code')
    )
    op.create_table('standard_formula_preparation',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('pbs_code', sa.String(length=50), nullable=False),
    sa.Column('sfp_drug_name', sa.String(length=500), nullable=True),
    sa.Column('sfp_reference', sa.String(length=500), nullable=True),
    sa.Column('container_fee', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dispensing_fee_max_quantity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('safety_net_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('maximum_patient_charge', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('maximum_quantity_unit', sa.String(length=50), nullable=True),
    sa.Column('maximum_quantity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'pbs_code')
    )
    op.create_table('summary_of_change',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('source_schedule_code', sa.String(length=20), nullable=False),
    sa.Column('target_effective_date', sa.String(length=20), nullable=True),
    sa.Column('source_effective_date', sa.String(length=20), nullable=True),
    sa.Column('target_revision_number', sa.Integer(), nullable=True),
    sa.Column('source_revision_number', sa.Integer(), nullable=True),
    sa.Column('target_publication_status', sa.String(length=20), nullable=True),
    sa.Column('source_publication_status', sa.String(length=20), nullable=True),
    sa.Column('changed_table', sa.String(length=50), nullable=True),
    sa.Column('changed_endpoint', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=10), nullable=True),
    sa.Column('sql_statement', sa.Text(), nullable=True),
    sa.Column('table_keys', sa.Text(), nullable=True),
    sa.Column('change_detail', sa.Text(), nullable=True),
    sa.Column('previous_detail', sa.Text(), nullable=True),
    sa.Column('deleted_ind', sa.String(length=1), nullable=True),
    sa.Column('new_ind', sa.String(length=1), nullable=True),
    sa.Column('modified_ind', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code', 'source_schedule_code')
    )
    op.create_table('sync_state',
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('last_synced_schedule_code', sa.String(length=20), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('records_synced', sa.String(length=50), nullable=True),
    sa.Column('sync_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('endpoint')
    )
    op.drop_table('item_organisation_relationship')
    op.drop_table('item_prescribing_text_relationship')
    op.drop_table('restriction_prescribing_text_relationship')
    op.drop_table('item_restriction_relationship')
    op.drop_table('item_atc_relationship')
    op.drop_index(op.f('idx_atc_level'), table_name='atc_code')
    op.drop_index(op.f('idx_atc_schedule_code'), table_name='atc_code')
    op.drop_index(op.f('idx_item_benefit_type_code'), table_name='item')
    op.drop_index(op.f('idx_item_brand_name'), table_name='item')
    op.drop_index(op.f('idx_item_drug_name'), table_name='item')
    op.drop_index(op.f('idx_item_first_listed_date'), table_name='item')
    op.drop_index(op.f('idx_item_non_effective_date'), table_name='item')
    op.drop_index(op.f('idx_item_pbs_code'), table_name='item')
    op.drop_index(op.f('idx_item_program_code'), table_name='item')
    op.drop_index(op.f('idx_item_schedule_code'), table_name='item')
    op.drop_index(op.f('idx_restriction_number'), table_name='restriction')
    op.drop_index(op.f('idx_restriction_schedule_code'), table_name='restriction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_restriction_schedule_code'), 'restriction', ['schedule_code'], unique=False)
    op.create_index(op.f('idx_restriction_number'), 'restriction', ['restriction_number'], unique=False)
    op.create_index(op.f('idx_item_schedule_code'), 'item', ['schedule_code'], unique=False)
    op.create_index(op.f('idx_item_program_code'), 'item', ['program_code'], unique=False)
    op.create_index(op.f('idx_item_pbs_code'), 'item', ['pbs_code'], unique=False)
    op.create_index(op.f('idx_item_non_effective_date'), 'item', ['non_effective_date'], unique=False)
    op.create_index(op.f('idx_item_first_listed_date'), 'item', ['first_listed_date'], unique=False)
    op.create_index(op.f('idx_item_drug_name'), 'item', ['drug_name'], unique=False)
    op.create_index(op.f('idx_item_brand_name'), 'item', ['brand_name'], unique=False)
    op.create_index(op.f('idx_item_benefit_type_code'), 'item', ['benefit_type_code'], unique=False)
    op.create_index(op.f('idx_atc_schedule_code'), 'atc_code', ['schedule_code'], unique=False)
    op.create_index(op.f('idx_atc_level'), 'atc_code', ['atc_level'], unique=False)
    op.create_table('item_atc_relationship',
    sa.Column('li_item_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('atc_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('schedule_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('atc_priority_pct', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('li_item_id', 'atc_code', 'schedule_code')
    )
    op.create_table('item_restriction_relationship',
    sa.Column('pbs_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('res_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('schedule_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('benefit_type_code', sa.VARCHAR(length=1), nullable=True),
    sa.Column('restriction_indicator', sa.VARCHAR(length=1), nullable=True),
    sa.Column('res_position', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'res_code', 'schedule_code')
    )
    op.create_table('restriction_prescribing_text_relationship',
    sa.Column('res_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prescribing_text_id', sa.INTEGER(), nullable=True),
    sa.Column('schedule_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pt_position', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('res_code', 'prescribing_text_id', 'schedule_code')
    )
    op.create_table('item_prescribing_text_relationship',
    sa.Column('pbs_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('prescribing_txt_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pt_position', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pbs_code', 'prescribing_txt_id', 'schedule_code')
    )
    op.create_table('item_organisation_relationship',
    sa.Column('li_item_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_code', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('li_item_id', 'organisation_id', 'schedule_code')
    )
    op.drop_table('sync_state')
    op.drop_table('summary_of_change')
    op.drop_table('standard_formula_preparation')
    op.drop_table('restriction_prescribing_text_relationships')
    op.drop_table('program_dispensing_rules')
    op.drop_table('program')
    op.drop_table('prescriber')
    op.drop_table('parameter')
    op.drop_table('markup_band')
    op.drop_table('item_restriction_relationships')
    op.drop_table('item_pricing_event')
    op.drop_table('item_prescribing_text_relationships')
    op.drop_table('item_organisation_relationships')
    op.drop_table('item_dispensing_rule_relationships')
    op.drop_table('item_atc_relationships')
    op.drop_table('extemporaneous_tariff')
    op.drop_table('extemporaneous_preparation')
    op.drop_table('extemporaneous_prep_sfp_relationships')
    op.drop_table('extemporaneous_ingredient')
    op.drop_table('dispensing_rule')
    op.drop_table('criterion')
    op.drop_table('criteria_parameter_relationships')
    op.drop_table('container_organisation_relationships')
    op.drop_table('container')
    op.drop_table('amt_item')
    # ### end Alembic commands ###
