"""initial_schema

Revision ID: bfb9b4e35082
Revises: 
Create Date: 2026-01-18 12:16:54.735904
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bfb9b4e35082"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atc_code',
    sa.Column('atc_code', sa.String(length=20), nullable=False),
    sa.Column('atc_description', sa.String(length=500), nullable=True),
    sa.Column('atc_level', sa.Integer(), nullable=True),
    sa.Column('atc_parent_code', sa.String(length=20), nullable=True),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('atc_code')
    )
    op.create_table('base_reference',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('general', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('concessional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_general', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_concessional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_card_issue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('increased_discount_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_ctg_contribution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('program_code', sa.String(length=10), nullable=True),
    sa.Column('dispensing_fee_ready_prepared', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee_dangerous_drug', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee_extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee_extemporaneous', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_recording_fee_ep', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_net_recording_fee_rp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee_water_added', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('container_fee_injectable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('container_fee_other', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gnrl_copay_discount_general', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gnrl_copay_discount_hospital', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('con_copay_discount_general', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('con_copay_discount_hospital', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efc_diluent_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efc_preparation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('efc_distribution_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acss_imdq60_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acss_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indication',
    sa.Column('indication_prescribing_txt_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=True),
    sa.Column('episodicity', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=100), nullable=True),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('indication_prescribing_txt_id')
    )
    op.create_table('item',
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('drug_name', sa.String(length=500), nullable=True),
    sa.Column('li_drug_name', sa.String(length=500), nullable=True),
    sa.Column('li_form', sa.String(length=500), nullable=True),
    sa.Column('schedule_form', sa.String(length=500), nullable=True),
    sa.Column('brand_name', sa.String(length=500), nullable=True),
    sa.Column('program_code', sa.String(length=10), nullable=True),
    sa.Column('pbs_code', sa.String(length=20), nullable=True),
    sa.Column('benefit_type_code', sa.String(length=1), nullable=True),
    sa.Column('caution_indicator', sa.String(length=1), nullable=True),
    sa.Column('note_indicator', sa.String(length=1), nullable=True),
    sa.Column('manner_of_administration', sa.String(length=100), nullable=True),
    sa.Column('moa_preferred_term', sa.String(length=100), nullable=True),
    sa.Column('maximum_prescribable_pack', sa.Integer(), nullable=True),
    sa.Column('maximum_quantity_units', sa.String(length=50), nullable=True),
    sa.Column('number_of_repeats', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_code', sa.String(length=20), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('pricing_quantity', sa.Integer(), nullable=True),
    sa.Column('pack_not_to_be_broken_ind', sa.String(length=1), nullable=True),
    sa.Column('claimed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('determined_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('determined_qty', sa.String(length=1), nullable=True),
    sa.Column('safety_net_resupply_rule_days', sa.Integer(), nullable=True),
    sa.Column('safety_net_resup_rule_cnt_ind', sa.String(length=1), nullable=True),
    sa.Column('extemporaneous_indicator', sa.String(length=1), nullable=True),
    sa.Column('extemporaneous_standard', sa.String(length=100), nullable=True),
    sa.Column('doctors_bag_group_id', sa.String(length=50), nullable=True),
    sa.Column('section100_only_indicator', sa.String(length=1), nullable=True),
    sa.Column('doctors_bag_only_indicator', sa.String(length=1), nullable=True),
    sa.Column('brand_substitution_group_id', sa.String(length=50), nullable=True),
    sa.Column('brand_substitution_group_code', sa.String(length=10), nullable=True),
    sa.Column('continued_dispensing_emergency', sa.String(length=1), nullable=True),
    sa.Column('continued_dispensing_flag', sa.String(length=1), nullable=True),
    sa.Column('supply_only_indicator', sa.String(length=1), nullable=True),
    sa.Column('supply_only_date', sa.Date(), nullable=True),
    sa.Column('non_effective_date', sa.Date(), nullable=True),
    sa.Column('originator_brand_indicator', sa.String(length=1), nullable=True),
    sa.Column('paper_med_chart_eligible_ind', sa.String(length=1), nullable=True),
    sa.Column('elect_med_chart_eligible_ind', sa.String(length=1), nullable=True),
    sa.Column('hsptl_med_chart_eligible_ind', sa.String(length=1), nullable=True),
    sa.Column('paper_med_chart_duration', sa.Integer(), nullable=True),
    sa.Column('elect_med_chart_duration', sa.Integer(), nullable=True),
    sa.Column('hsptl_chart_acute_duration', sa.Integer(), nullable=True),
    sa.Column('hsptl_chart_sub_acute_duration', sa.Integer(), nullable=True),
    sa.Column('hsptl_chart_chronic_duration', sa.Integer(), nullable=True),
    sa.Column('pack_content', sa.Integer(), nullable=True),
    sa.Column('vial_content', sa.String(length=50), nullable=True),
    sa.Column('infusible_indicator', sa.String(length=1), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('maximum_amount', sa.String(length=50), nullable=True),
    sa.Column('formulary', sa.String(length=10), nullable=True),
    sa.Column('water_added_ind', sa.String(length=1), nullable=True),
    sa.Column('section_19a_expiry_date', sa.Date(), nullable=True),
    sa.Column('container_fee_type', sa.String(length=50), nullable=True),
    sa.Column('policy_applied_bio_sim_up_flag', sa.String(length=1), nullable=True),
    sa.Column('policy_applied_imdq60_flag', sa.String(length=1), nullable=True),
    sa.Column('policy_applied_imdq60_base_flag', sa.String(length=1), nullable=True),
    sa.Column('policy_applied_indig_phar_flag', sa.String(length=1), nullable=True),
    sa.Column('therapeutic_exemption_indicator', sa.String(length=1), nullable=True),
    sa.Column('premium_exemption_group_id', sa.String(length=50), nullable=True),
    sa.Column('doctors_bag_group_title', sa.String(length=200), nullable=True),
    sa.Column('therapeutic_group_id', sa.String(length=50), nullable=True),
    sa.Column('therapeutic_group_title', sa.String(length=200), nullable=True),
    sa.Column('advanced_notice_date', sa.Date(), nullable=True),
    sa.Column('supply_only_end_date', sa.Date(), nullable=True),
    sa.Column('first_listed_date', sa.Date(), nullable=True),
    sa.Column('legal_unar_ind', sa.String(length=1), nullable=True),
    sa.Column('legal_car_ind', sa.String(length=1), nullable=True),
    sa.Column('proportional_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('li_substitution_group_id', sa.String(length=50), nullable=True),
    sa.Column('innovator_indicator', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('li_item_id')
    )
    op.create_table('item_atc_relationship',
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('atc_code', sa.String(length=20), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('atc_priority_pct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('li_item_id', 'atc_code', 'schedule_code')
    )
    op.create_table('item_organisation_relationship',
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('li_item_id', 'organisation_id', 'schedule_code')
    )
    op.create_table('item_restriction_relationship',
    sa.Column('li_item_id', sa.String(length=100), nullable=False),
    sa.Column('res_code', sa.String(length=100), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('res_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('li_item_id', 'res_code', 'schedule_code')
    )
    op.create_table('organisation',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('street_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('telephone_number', sa.String(length=50), nullable=True),
    sa.Column('facsimile_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('organisation_id')
    )
    op.create_table('prescribing_text',
    sa.Column('prescribing_txt_id', sa.Integer(), nullable=False),
    sa.Column('prescribing_txt', sa.String(), nullable=True),
    sa.Column('prescribing_type', sa.String(length=100), nullable=True),
    sa.Column('complex_authority_rqrd_ind', sa.String(length=1), nullable=True),
    sa.Column('assessment_type_code', sa.String(length=50), nullable=True),
    sa.Column('apply_to_increase_mq_flag', sa.String(length=1), nullable=True),
    sa.Column('apply_to_increase_nr_flag', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('prescribing_txt_id')
    )
    op.create_table('restriction',
    sa.Column('res_code', sa.String(length=100), nullable=False),
    sa.Column('schedule_code', sa.String(length=20), nullable=True),
    sa.Column('restriction_number', sa.Integer(), nullable=True),
    sa.Column('treatment_of_code', sa.Integer(), nullable=True),
    sa.Column('authority_method', sa.String(length=50), nullable=True),
    sa.Column('treatment_phase', sa.String(length=100), nullable=True),
    sa.Column('note_indicator', sa.String(length=1), nullable=True),
    sa.Column('caution_indicator', sa.String(length=1), nullable=True),
    sa.Column('complex_authority_rqrd_ind', sa.String(length=1), nullable=True),
    sa.Column('assessment_type_code', sa.String(length=50), nullable=True),
    sa.Column('criteria_relationship', sa.String(length=10), nullable=True),
    sa.Column('variation_rule_applied', sa.String(length=1), nullable=True),
    sa.Column('first_listing_date', sa.Date(), nullable=True),
    sa.Column('written_authority_required', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('res_code')
    )
    op.create_table('schedule',
    sa.Column('schedule_code', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_month', sa.String(length=20), nullable=True),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('start_tsp', sa.TIMESTAMP(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('publication_status', sa.String(length=20), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_code')
    )
    op.create_index('idx_atc_level', 'atc_code', ['atc_level'], unique=False)
    op.create_index('idx_atc_schedule_code', 'atc_code', ['schedule_code'], unique=False)
    op.create_index('idx_item_benefit_type_code', 'item', ['benefit_type_code'], unique=False)
    op.create_index('idx_item_brand_name', 'item', ['brand_name'], unique=False)
    op.create_index('idx_item_drug_name', 'item', ['drug_name'], unique=False)
    op.create_index('idx_item_first_listed_date', 'item', ['first_listed_date'], unique=False)
    op.create_index('idx_item_non_effective_date', 'item', ['non_effective_date'], unique=False)
    op.create_index('idx_item_pbs_code', 'item', ['pbs_code'], unique=False)
    op.create_index('idx_item_program_code', 'item', ['program_code'], unique=False)
    op.create_index('idx_item_schedule_code', 'item', ['schedule_code'], unique=False)
    op.create_index('idx_restriction_number', 'restriction', ['restriction_number'], unique=False)
    op.create_index('idx_restriction_schedule_code', 'restriction', ['schedule_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restriction_schedule_code', table_name='restriction')
    op.drop_index('idx_restriction_number', table_name='restriction')
    op.drop_index('idx_item_schedule_code', table_name='item')
    op.drop_index('idx_item_program_code', table_name='item')
    op.drop_index('idx_item_pbs_code', table_name='item')
    op.drop_index('idx_item_non_effective_date', table_name='item')
    op.drop_index('idx_item_first_listed_date', table_name='item')
    op.drop_index('idx_item_drug_name', table_name='item')
    op.drop_index('idx_item_brand_name', table_name='item')
    op.drop_index('idx_item_benefit_type_code', table_name='item')
    op.drop_index('idx_atc_schedule_code', table_name='atc_code')
    op.drop_index('idx_atc_level', table_name='atc_code')
    op.drop_table('schedule')
    op.drop_table('restriction')
    op.drop_table('prescribing_text')
    op.drop_table('organisation')
    op.drop_table('item_restriction_relationship')
    op.drop_table('item_organisation_relationship')
    op.drop_table('item_atc_relationship')
    op.drop_table('item')
    op.drop_table('indication')
    op.drop_table('fee')
    op.drop_table('copayment')
    op.drop_table('base_reference')
    op.drop_table('atc_code')
    # ### end Alembic commands ###
